# secrets.properties
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
oauth.client.id=${OAUTH_CLIENT_ID}
oauth.client.secret=${OAUTH_CLIENT_SECRET}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}